/*
 * Copyright 2020 Francis Wang
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package verikc.base.config

import verikc.base.symbol.SymbolContext
import verikc.main.VERSION
import java.io.File

enum class CompileScopeType {
    TOP,
    ALL;

    companion object {

        operator fun invoke(string: String?): CompileScopeType {
            return when (string) {
                null -> TOP
                "top" -> TOP
                "all" -> ALL
                else -> throw java.lang.IllegalArgumentException("illegal compile scope $string")
            }
        }
    }
}

data class ProjectConfig(
    val timeString: String,
    val configFile: File,
    val projectDir: File,
    val project: String,
    val buildDir: File,
    val buildCopyDir: File,
    val buildCacheDir: File,
    val buildOutDir: File,
    val symbolContext: SymbolContext,
    val gradle: ProjectGradleConfig,
    val compile: ProjectCompileConfig,
    val rconf: ProjectRconfConfig?,
    val compilationUnit: CompilationUnitConfig
) {

    val configCopyFile = buildDir.resolve("vkproject.yaml")
    val hashFile = buildDir.resolve("hash.txt")
    val orderFile = buildDir.resolve("order.txt")
    val rconfFile = buildDir.resolve("rconf.txt")

    fun header(inFile: File, outFile: File): String {
        return """
            ////////////////////////////////////////////////////////////////////////////////
            //  GENERATED BY VERIKC $VERSION
            //  Date:     $timeString
            //  Project:  $project
            //  File:     ${outFile.relativeTo(projectDir)}
            //  Source:   ${inFile.relativeTo(projectDir)}
            ////////////////////////////////////////////////////////////////////////////////
            
        """.trimIndent()
    }

    companion object {

        operator fun invoke(configPath: String): ProjectConfig {
            return ConfigLoader.loadProjectConfig(configPath)
        }
    }
}

data class ProjectGradleConfig(
    val dir: File,
    val wrapperSh: File,
    val wrapperBat: File
)

data class ProjectCompileConfig(
    val top: String?,
    val scopeType: CompileScopeType,
    val labelLines: Boolean
)

data class ProjectRconfConfig(
    val main: String,
    val jar: File
)
