/*
 * Copyright 2020 Francis Wang
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package verik.core.main

import verik.core.main.config.ProjectConfig
import java.io.File

object FileHeaderBuilder {

    private const val LINES = 8

    fun build(config: ProjectConfig, source: File, out: File): String {
        return """
            ////////////////////////////////////////////////////////////////////////////////
            //  GENERATED BY VERIK-$VERSION
            //  Date:     ${config.timeString}
            //  Project:  ${config.project}
            //  File:     ${out.relativeTo(config.projectDir)}
            //  Source:   ${source.relativeTo(config.projectDir)}
            ////////////////////////////////////////////////////////////////////////////////
            
        """.trimIndent()
    }

    fun strip(fileString: String): String {
        var index = -1
        repeat (LINES) {
            index = fileString.indexOf("\n", index + 1)
        }
        return fileString.substring(index + 1)
    }
}