package com.verik.core

import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.stream.IntStream


// Copyright (c) 2020 Francis Wang

inline fun indent(builder: SourceBuilder, block: () -> Unit) {
    builder.indent++
    block()
    builder.indent--
}

inline fun label(builder: SourceBuilder, line: Int, block: () -> Unit) {
    builder.line = line
    block()
    builder.line = null
}

class SourceBuilder private constructor(private val labelLineNumbers: Boolean, private val labelLength: Int) {

    private val builder = StringBuilder()
    private var newLine = true
    var indent = 0
    var line: Int? = null

    constructor(): this(false, 0)

    constructor(conf: ProjConf, labelLength: Int): this(conf.labelLineNumbers, labelLength) {
        val current = LocalDateTime.now()
        val formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy HH:mm:ss")
        val formatted = current.format(formatter)

        builder.appendln("""
            ////////////////////////////////////////////////////////////////////////////////
            //  GENERATED BY VERIK-$VERSION
            //  Date:     $formatted
            //  Project:  ${conf.project}
            //  File:     ${conf.dstFile.relativeTo(conf.projDir)}
            //  Source:   ${conf.srcFile.relativeTo(conf.projDir)}
            ////////////////////////////////////////////////////////////////////////////////
        """.trimIndent())
        builder.appendln()

        if (labelLineNumbers) {
            builder.appendln("`define _(N)")
            builder.appendln()
        }
    }

    fun append(string: String) {
        appendStream(string.chars())
    }

    fun appendln(string: String) {
        appendStream(string.chars())
        appendStream(IntStream.of('\n'.toInt()))
    }

    fun appendln() {
        appendStream(IntStream.of('\n'.toInt()))
    }

    override fun toString() = builder.toString()

    private fun appendStream(chars: IntStream) {
        for (char in chars) {
            if (char == '\n'.toInt()) {
                if (newLine && labelLineNumbers) builder.append(getLabel())
                builder.append("\n")
                newLine = true
            } else {
                if (newLine) {
                    if (labelLineNumbers) builder.append("${getLabel()}    ")
                    builder.append("  ".repeat(indent))
                    newLine = false
                }
                builder.appendCodePoint(char)
            }
        }
    }

    private fun getLabel(): String {
        return if (line != null) {
            "`_(${line.toString().padStart(labelLength, '0')})"
        } else {
            "`_(${" ".repeat(labelLength)})"
        }
    }
}