@file:Suppress("UNUSED_PARAMETER", "unused")

package com.verik.ref.basic_uvm

// generated by verik

infix fun _reg_ctrl.con(block: (_reg_ctrl) -> Unit) = this
infix fun _reg_if.con(block: (_reg_if) -> Unit) = this
infix fun _reg_if.con(x: _reg_if?) {}
infix fun _tb.con(block: (_tb) -> Unit) = this
