/*
 * SPDX-License-Identifier: Apache-2.0
 */

@file:Suppress("unused", "UNUSED_PARAMETER")

package io.verik.core

/**
 * Represents a value that is imported from SystemVerilog. It is generated by the importer and should not be used
 * directly.
 */
fun <T> imp(): T {
    throw VerikException()
}

/**
 * Inject [content] directly as a SystemVerilog statement. To inject an expression inline use [inji].
 */
fun inj(content: String) {
    throw VerikException()
}

/**
 * Inject [content] directly as an inline SystemVerilog expression. The injected expression has type [T]. To inject a
 * statement use [inj].
 */
fun <T> inji(content: String): T {
    throw VerikException()
}

/**
 * Returns the SystemVerilog representation of type [T]. This should only be used in injected string literals to inject
 * the type [T].
 *
 *  ```
 *  class C : Class() {
 *
 *      @Inj
 *      val macro = "`macro(${t<C>()})"
 *  }
 *  ```
 */
fun <T> t(): String {
    throw VerikException()
}

/**
 * Represents a value that is not connected in port connections or property declarations.
 */
fun <T> nc(): T {
    throw VerikException()
}

/**
 * (UNIMPLEMENTED) Construct a [Sequence] that evaluates [value] on the current cycle.
 */
fun q(value: Boolean): Sequence {
    throw VerikException()
}

/**
 * Construct a randomization constraint from [conditions].
 */
fun c(vararg conditions: Boolean): Constraint {
    throw VerikException()
}

/**
 * Construct a [CoverPoint] for [value]. Optionally, specify the [bins] to be used. [bins] will be injected as
 * SystemVerilog.
 */
fun cp(value: Any, vararg bins: String): CoverPoint {
    throw VerikException()
}

/**
 * Construct a [CoverCross] for cover points [x] and [y]. Optionally, specify the [bins] to be used. [bins] will be
 * injected as SystemVerilog.
 */
fun cc(x: CoverPoint, y: CoverPoint, vararg bins: String): CoverCross {
    throw VerikException()
}

/**
 * Construct a [CoverCross] for cover points [x], [y], and [z]. Optionally, specify the [bins] to be used. [bins] will
 * be injected as SystemVerilog.
 */
fun cc(x: CoverPoint, y: CoverPoint, z: CoverPoint, vararg bins: String): CoverCross {
    throw VerikException()
}

/**
 * (UNIMPLEMENTED) Pack [value] as a [Ubit].
 */
fun pack(value: Any): Ubit<`*`> {
    throw VerikException()
}

/**
 * (UNIMPLEMENTED) Unpack [value] to type [T].
 */
fun <T> unpack(value: Ubit<`*`>): T {
    throw VerikException()
}

/**
 * Conditionally instantiate [T] based on [value]. [value] must be a compile time constant.
 */
fun <T> optional(value: Boolean, instantiator: () -> T): T? {
    throw VerikException()
}

/**
 * Instantiate a [Cluster] of type [T] with [size] members. [size] must be a compile time constant.
 */
fun <T> cluster(size: Int, instantiator: (Int) -> T): Cluster<`*`, T> {
    throw VerikException()
}
