/*
 * SPDX-License-Identifier: Apache-2.0
 */

package io.verik.importer.core

import io.verik.importer.ast.common.Declaration

/**
 * The base class of all core declarations. Core declarations are declarations defined in the Kotlin standard library or
 * the Verik core package that can be referenced by code generated by the importer.
 */
interface CoreDeclaration : Declaration
