name: Sanity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2.2.0
        with:
          java-version: 11
          distribution: 'adopt'
      - uses: eskatos/gradle-command-action@v1.4.1
        with:
          arguments: sanity
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
