name: Sanity

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Run Checks
        uses: eskatos/gradle-command-action@v1.4.1
        with:
          arguments: mainCheck
          distributions-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
